inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require:
  - rubocop-faker
  - rubocop-i18n
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
AllCops:
  Exclude:
    - ".bundle/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
  DisplayCopNames:                     true
  NewCops:                             enable

Style/FrozenStringLiteralComment:
  EnforcedStyle:                       never
