inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require:
  - rubocop-faker
  - rubocop-i18n
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
AllCops:
  Exclude:
    - ".bundle/**/*"
    - "bin/bundle"
    - "config/initializers/devise.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
  DisplayCopNames:                true
  NewCops:                        enable

Layout/LineLength:
  Max:                            120
Style/FrozenStringLiteralComment:
  EnforcedStyle:                  never
